export const UPDATE_FUNCTION_FORM = 'UPDATE_FUNCTION_FORM';
export const UPDATE_PLOTTING_DATA = 'UPDATE_PLOTTING_DATA';
export const GLOBAL_SNACKBAR = 'GLOBAL_SNACKBAR';
export const GLOBAL_LINEAR_PROGRESS = 'GLOBAL_LINEAR_PROGRESS';