export const UPDATE_FUNCTION_FORM = 'UPDATE_FUNCTION_FORM';
export const UPDATE_PLOTTING_DATA = 'UPDATE_PLOTTING_DATA';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
