const {REACT_APP_PROTOCOL, REACT_APP_PORT, REACT_APP_SERVER_ADDRESS} = process.env;

const endpoints = {
    SHARE_PLOT_ENDPOINT: '/vis-plot/',
    SHARE_GRAPH_ENDPOINT: '/vis-graph/'
};

const API = {
    SHARE_PLOT_URL: `${REACT_APP_PROTOCOL}://${REACT_APP_SERVER_ADDRESS}:${REACT_APP_PORT}${endpoints.SHARE_PLOT_ENDPOINT}`,
    SHARE_GRAPH_URL: `${REACT_APP_PROTOCOL}://${REACT_APP_SERVER_ADDRESS}:${REACT_APP_PORT}${endpoints.SHARE_GRAPH_ENDPOINT}`
};

export default API;